---

- hosts: all
  become: true
  tasks:

  - name: Install apache and php packages
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: Install apache httpd  (state=present is optional)
    ansible.builtin.yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: (ansible_pkg_mgr == 'yum') and (ansible_distribution == "CentOS")
