---
 
- hosts: all
  become: true
  pre_tasks:
 
   - name: update repository index (CentOS)
     tags: always
     ansible.builtin.yum:
       update_cache: yes
     changed_when: false
     when: (ansible_pkg_mgr == 'yum') and (ansible_distribution == "CentOS")
 
   - name: update repository index (Ubuntu)
     tags: always
     apt:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "Debian"
 
- hosts: all
  become: true
  roles:
     - base
    
- hosts: work_stations
  become: true
  roles:
    - workstations
 
- hosts: web_servers
  become: true
  roles:
    - web_servers
 
- hosts: file_servers
  become: true
  roles:
    - file_servers
