- name: Install apache and php packages
  tags: apache,apache2,Debian
  package:
    name: 
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Debian"

- name: Install apache httpd
  tags: apache,centos.httpd
  ansible.builtin.yum:
    name:
      - httpd
      - php
    state: latest
  when: (ansible_pkg_mgr == 'yum') and (ansible_distribution == "CentOS")

- name: start httpd (CentOS)
  tags: apche,centos,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: (ansible_pkg_mgr == 'yum') and (ansible_distribution == "CentOS")

- name: change email address for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: (ansible_pkg_mgr == 'yum') and (ansible_distribution == "CentOS")
  register: httpd

- name: restart httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
